spring.application.name=auth-service

server.port=8082

keycloak.server-url=http://localhost:8080

keycloak.admin-realm=master

keycloak.app-realm=swoovo-dev

keycloak.admin-username=admin

keycloak.admin-password=admin

keycloak.client-id=admin-cli

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=TRACE

eureka.client.enabled=false

jwt.secret=super-secret-key-super-secret-key
jwt.access_token.expiration_time=600000
jwt.refresh_token.expiration_time=10080000

google.client-id = 857664454254-b6quuq12b1lfvs1v1b1ovjp5aon3ks2h.apps.googleusercontent.com