spring.application.name=notification-service

server.port=9000

firebase.service.account-file=firebase/firebase-service-account.json

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=demenchuk1210m@gmail.com
spring.mail.password=uaaj ipfe mfwp bdnh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=ACaa2e4484abf5ba399d888918f7b583dc

twilio.auth.token=2fe1504453fc17fcc5d814a7c886d837

twilio.phone.number=+14174412470

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

management.endpoints.web.exposure.include=health,info,metrics

resilience4j.retry.metrics.enabled=true
resilience4j.retry.instances.notification-service.maxAttempts=3
resilience4j.retry.instances.notification-service.waitDuration=1s
resilience4j.retry.instances.notification-service.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.instances.notification-service.retryExceptions[1]=java.io.IOException
resilience4j.retry.instances.notification-service.ignoreExceptions[0]=org.springframework.web.client.HttpClientErrorException

