server.port=8100

spring.application.name=post-service
spring.datasource.url=jdbc:postgresql://localhost:5432/postsdb
spring.datasource.username=postgres
spring.datasource.password=12102021egorDem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.max-http-form-post-size=500MB
server.tomcat.max-swallow-size=500MB

minio.url=http://localhost:9000
minio.secret-key=minioadmin
minio.access-key=minioadmin
minio.bucket-name=avatars
minio.expiration=360

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

management.endpoints.web.exposure.include=health,info,metrics

resilience4j.retry.metrics.enabled=true
resilience4j.retry.instances.post-service.maxAttempts=3
resilience4j.retry.instances.post-service.waitDuration=1s
resilience4j.retry.instances.post-service.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.instances.post-service.retryExceptions[1]=java.io.IOException
resilience4j.retry.instances.post-service.ignoreExceptions[0]=org.springframework.web.client.HttpClientErrorException